import { Injectable } from '@angular/core';
import { ProvinciasModel } from 'src/models/provincia';

@Injectable({
  providedIn: 'root'
})
export class ProvinciasService {

  private provinciaList: ProvinciasModel[] = [
    {id_provincia: 1, id_departamento: 1, ubigeo_provincia: "010100", nombre_provincia: "Chachapoyas"},
    {id_provincia: 2, id_departamento: 1, ubigeo_provincia: "010200", nombre_provincia: "Bagua"},
    {id_provincia: 3, id_departamento: 1, ubigeo_provincia: "010300", nombre_provincia: "Bongara"},
    {id_provincia: 4, id_departamento: 1, ubigeo_provincia: "010400", nombre_provincia: "Condorcanqui"},
    {id_provincia: 5, id_departamento: 1, ubigeo_provincia: "010500", nombre_provincia: "Luya"},
    {id_provincia: 6, id_departamento: 1, ubigeo_provincia: "010600", nombre_provincia: "Rodriguez de Mendoza"},
    {id_provincia: 7, id_departamento: 1, ubigeo_provincia: "010700", nombre_provincia: "Utcubamba"},
    {id_provincia: 8, id_departamento: 2, ubigeo_provincia: "020100", nombre_provincia: "Huaraz"},
    {id_provincia: 9, id_departamento: 2, ubigeo_provincia: "020200", nombre_provincia: "Aija"},
    {id_provincia: 10, id_departamento: 2, ubigeo_provincia: "020300", nombre_provincia: "Antonio Raymondi"},
    {id_provincia: 11, id_departamento: 2, ubigeo_provincia: "020400", nombre_provincia: "Asuncion"},
    {id_provincia: 12, id_departamento: 2, ubigeo_provincia: "020500", nombre_provincia: "Bolognesi"},
    {id_provincia: 13, id_departamento: 2, ubigeo_provincia: "020600", nombre_provincia: "Carhuaz"},
    {id_provincia: 14, id_departamento: 2, ubigeo_provincia: "020700", nombre_provincia: "Carlos Fermin Fitzcarrald"},
    {id_provincia: 15, id_departamento: 2, ubigeo_provincia: "020800", nombre_provincia: "Casma"},
    {id_provincia: 16, id_departamento: 2, ubigeo_provincia: "020900", nombre_provincia: "Corongo"},
    {id_provincia: 17, id_departamento: 2, ubigeo_provincia: "021000", nombre_provincia: "Huari"},
    {id_provincia: 18, id_departamento: 2, ubigeo_provincia: "021100", nombre_provincia: "Huarmey"},
    {id_provincia: 19, id_departamento: 2, ubigeo_provincia: "021200", nombre_provincia: "Huaylas"},
    {id_provincia: 20, id_departamento: 2, ubigeo_provincia: "021300", nombre_provincia: "Mariscal Luzuriaga"},
    {id_provincia: 21, id_departamento: 2, ubigeo_provincia: "021400", nombre_provincia: "Ocros"},
    {id_provincia: 22, id_departamento: 2, ubigeo_provincia: "021500", nombre_provincia: "Pallasca"},
    {id_provincia: 23, id_departamento: 2, ubigeo_provincia: "021600", nombre_provincia: "Pomabamba"},
    {id_provincia: 24, id_departamento: 2, ubigeo_provincia: "021700", nombre_provincia: "Recuay"},
    {id_provincia: 25, id_departamento: 2, ubigeo_provincia: "021800", nombre_provincia: "Santa"},
    {id_provincia: 26, id_departamento: 2, ubigeo_provincia: "021900", nombre_provincia: "Sihuas"},
    {id_provincia: 27, id_departamento: 2, ubigeo_provincia: "022000", nombre_provincia: "Yungay"},
    {id_provincia: 28, id_departamento: 3, ubigeo_provincia: "030100", nombre_provincia: "Abancay"},
    {id_provincia: 29, id_departamento: 3, ubigeo_provincia: "030200", nombre_provincia: "Andahuaylas"},
    {id_provincia: 30, id_departamento: 3, ubigeo_provincia: "030300", nombre_provincia: "Antabamba"},
    {id_provincia: 31, id_departamento: 3, ubigeo_provincia: "030400", nombre_provincia: "Aymaraes"},
    {id_provincia: 32, id_departamento: 3, ubigeo_provincia: "030500", nombre_provincia: "Cotabambas"},
    {id_provincia: 33, id_departamento: 3, ubigeo_provincia: "030600", nombre_provincia: "Chincheros"},
    {id_provincia: 34, id_departamento: 3, ubigeo_provincia: "030700", nombre_provincia: "Grau"},
    {id_provincia: 35, id_departamento: 4, ubigeo_provincia: "040100", nombre_provincia: "Arequipa"},
    {id_provincia: 36, id_departamento: 4, ubigeo_provincia: "040200", nombre_provincia: "Camana"},
    {id_provincia: 37, id_departamento: 4, ubigeo_provincia: "040300", nombre_provincia: "Caraveli"},
    {id_provincia: 38, id_departamento: 4, ubigeo_provincia: "040400", nombre_provincia: "Castilla"},
    {id_provincia: 39, id_departamento: 4, ubigeo_provincia: "040500", nombre_provincia: "Caylloma"},
    {id_provincia: 40, id_departamento: 4, ubigeo_provincia: "040600", nombre_provincia: "Condesuyos"},
    {id_provincia: 41, id_departamento: 4, ubigeo_provincia: "040700", nombre_provincia: "Islay"},
    {id_provincia: 42, id_departamento: 4, ubigeo_provincia: "040800", nombre_provincia: "La Union"},
    {id_provincia: 43, id_departamento: 5, ubigeo_provincia: "050100", nombre_provincia: "Huamanga"},
    {id_provincia: 44, id_departamento: 5, ubigeo_provincia: "050200", nombre_provincia: "Cangallo"},
    {id_provincia: 45, id_departamento: 5, ubigeo_provincia: "050300", nombre_provincia: "Huanca Sancos"},
    {id_provincia: 46, id_departamento: 5, ubigeo_provincia: "050400", nombre_provincia: "Huanta"},
    {id_provincia: 47, id_departamento: 5, ubigeo_provincia: "050500", nombre_provincia: "La Mar"},
    {id_provincia: 48, id_departamento: 5, ubigeo_provincia: "050600", nombre_provincia: "Lucanas"},
    {id_provincia: 49, id_departamento: 5, ubigeo_provincia: "050700", nombre_provincia: "Parinacochas"},
    {id_provincia: 50, id_departamento: 5, ubigeo_provincia: "050800", nombre_provincia: "Paucar del Sara Sara"},
    {id_provincia: 51, id_departamento: 5, ubigeo_provincia: "050900", nombre_provincia: "Sucre"},
    {id_provincia: 52, id_departamento: 5, ubigeo_provincia: "051000", nombre_provincia: "Victor Fajardo"},
    {id_provincia: 53, id_departamento: 5, ubigeo_provincia: "051100", nombre_provincia: "Vilcas Huaman"},
    {id_provincia: 54, id_departamento: 6, ubigeo_provincia: "060100", nombre_provincia: "Cajamarca"},
    {id_provincia: 55, id_departamento: 6, ubigeo_provincia: "060200", nombre_provincia: "Cajabamba"},
    {id_provincia: 56, id_departamento: 6, ubigeo_provincia: "060300", nombre_provincia: "Celendin"},
    {id_provincia: 57, id_departamento: 6, ubigeo_provincia: "060400", nombre_provincia: "Chota"},
    {id_provincia: 58, id_departamento: 6, ubigeo_provincia: "060500", nombre_provincia: "Contumaza"},
    {id_provincia: 59, id_departamento: 6, ubigeo_provincia: "060600", nombre_provincia: "Cutervo"},
    {id_provincia: 60, id_departamento: 6, ubigeo_provincia: "060700", nombre_provincia: "Hualgayoc"},
    {id_provincia: 61, id_departamento: 6, ubigeo_provincia: "060800", nombre_provincia: "Jaen"},
    {id_provincia: 62, id_departamento: 6, ubigeo_provincia: "060900", nombre_provincia: "San Ignacio"},
    {id_provincia: 63, id_departamento: 6, ubigeo_provincia: "061000", nombre_provincia: "San Marcos"},
    {id_provincia: 64, id_departamento: 6, ubigeo_provincia: "061100", nombre_provincia: "San Miguel"},
    {id_provincia: 65, id_departamento: 6, ubigeo_provincia: "061200", nombre_provincia: "San Pablo"},
    {id_provincia: 66, id_departamento: 6, ubigeo_provincia: "061300", nombre_provincia: "Santa Cruz"},
    {id_provincia: 67, id_departamento: 7, ubigeo_provincia: "070100", nombre_provincia: "Prov. Const. del Callao"},
    {id_provincia: 68, id_departamento: 8, ubigeo_provincia: "080100", nombre_provincia: "Cusco"},
    {id_provincia: 69, id_departamento: 8, ubigeo_provincia: "080200", nombre_provincia: "Acomayo"},
    {id_provincia: 70, id_departamento: 8, ubigeo_provincia: "080300", nombre_provincia: "Anta"},
    {id_provincia: 71, id_departamento: 8, ubigeo_provincia: "080400", nombre_provincia: "Calca"},
    {id_provincia: 72, id_departamento: 8, ubigeo_provincia: "080500", nombre_provincia: "Canas"},
    {id_provincia: 73, id_departamento: 8, ubigeo_provincia: "080600", nombre_provincia: "Canchis"},
    {id_provincia: 74, id_departamento: 8, ubigeo_provincia: "080700", nombre_provincia: "Chumbivilcas"},
    {id_provincia: 75, id_departamento: 8, ubigeo_provincia: "080800", nombre_provincia: "Espinar"},
    {id_provincia: 76, id_departamento: 8, ubigeo_provincia: "080900", nombre_provincia: "La Convencion"},
    {id_provincia: 77, id_departamento: 8, ubigeo_provincia: "081000", nombre_provincia: "Paruro"},
    {id_provincia: 78, id_departamento: 8, ubigeo_provincia: "081100", nombre_provincia: "Paucartambo"},
    {id_provincia: 79, id_departamento: 8, ubigeo_provincia: "081200", nombre_provincia: "Quispicanchi"},
    {id_provincia: 80, id_departamento: 8, ubigeo_provincia: "081300", nombre_provincia: "Urubamba"},
    {id_provincia: 81, id_departamento: 9, ubigeo_provincia: "090100", nombre_provincia: "Huancavelica"},
    {id_provincia: 82, id_departamento: 9, ubigeo_provincia: "090200", nombre_provincia: "Acobamba"},
    {id_provincia: 83, id_departamento: 9, ubigeo_provincia: "090300", nombre_provincia: "Angaraes"},
    {id_provincia: 84, id_departamento: 9, ubigeo_provincia: "090400", nombre_provincia: "Castrovirreyna"},
    {id_provincia: 85, id_departamento: 9, ubigeo_provincia: "090500", nombre_provincia: "Churcampa"},
    {id_provincia: 86, id_departamento: 9, ubigeo_provincia: "090600", nombre_provincia: "Huaytara"},
    {id_provincia: 87, id_departamento: 9, ubigeo_provincia: "090700", nombre_provincia: "Tayacaja"},
    {id_provincia: 88, id_departamento: 10, ubigeo_provincia: "100100", nombre_provincia: "Huanuco"},
    {id_provincia: 89, id_departamento: 10, ubigeo_provincia: "100200", nombre_provincia: "Ambo"},
    {id_provincia: 90, id_departamento: 10, ubigeo_provincia: "100300", nombre_provincia: "Dos de Mayo"},
    {id_provincia: 91, id_departamento: 10, ubigeo_provincia: "100400", nombre_provincia: "Huacaybamba"},
    {id_provincia: 92, id_departamento: 10, ubigeo_provincia: "100500", nombre_provincia: "Huamalies"},
    {id_provincia: 93, id_departamento: 10, ubigeo_provincia: "100600", nombre_provincia: "Leoncio Prado"},
    {id_provincia: 94, id_departamento: 10, ubigeo_provincia: "100700", nombre_provincia: "Marañon"},
    {id_provincia: 95, id_departamento: 10, ubigeo_provincia: "100800", nombre_provincia: "Pachitea"},
    {id_provincia: 96, id_departamento: 10, ubigeo_provincia: "100900", nombre_provincia: "Puerto Inca"},
    {id_provincia: 97, id_departamento: 10, ubigeo_provincia: "101000", nombre_provincia: "Lauricocha"},
    {id_provincia: 98, id_departamento: 10, ubigeo_provincia: "101100", nombre_provincia: "Yarowilca"},
    {id_provincia: 99, id_departamento: 10, ubigeo_provincia: "110100", nombre_provincia: "Ica"},
    {id_provincia: 100, id_departamento: 11, ubigeo_provincia: "110200", nombre_provincia: "Chincha"},
    {id_provincia: 101, id_departamento: 11, ubigeo_provincia: "110300", nombre_provincia: "Nazca"},
    {id_provincia: 102, id_departamento: 11, ubigeo_provincia: "110400", nombre_provincia: "Palpa"},
    {id_provincia: 103, id_departamento: 11, ubigeo_provincia: "110500", nombre_provincia: "Pisco"},
    {id_provincia: 104, id_departamento: 12, ubigeo_provincia: "120100", nombre_provincia: "Huancayo"},
    {id_provincia: 105, id_departamento: 12, ubigeo_provincia: "120200", nombre_provincia: "Concepcion"},
    {id_provincia: 106, id_departamento: 12, ubigeo_provincia: "120300", nombre_provincia: "Chanchamayo"},
    {id_provincia: 107, id_departamento: 12, ubigeo_provincia: "120400", nombre_provincia: "Jauja"},
    {id_provincia: 108, id_departamento: 12, ubigeo_provincia: "120500", nombre_provincia: "Junin"},
    {id_provincia: 109, id_departamento: 12, ubigeo_provincia: "120600", nombre_provincia: "Satipo"},
    {id_provincia: 110, id_departamento: 12, ubigeo_provincia: "120700", nombre_provincia: "Tarma"},
    {id_provincia: 111, id_departamento: 12, ubigeo_provincia: "120800", nombre_provincia: "Yauli"},
    {id_provincia: 112, id_departamento: 12, ubigeo_provincia: "120900", nombre_provincia: "Chupaca"},
    {id_provincia: 113, id_departamento: 13, ubigeo_provincia: "130100", nombre_provincia: "Trujillo"},
    {id_provincia: 114, id_departamento: 13, ubigeo_provincia: "130200", nombre_provincia: "Ascope"},
    {id_provincia: 115, id_departamento: 13, ubigeo_provincia: "130300", nombre_provincia: "Bolivar"},
    {id_provincia: 116, id_departamento: 13, ubigeo_provincia: "130400", nombre_provincia: "Chepen"},
    {id_provincia: 117, id_departamento: 13, ubigeo_provincia: "130500", nombre_provincia: "Julcan"},
    {id_provincia: 118, id_departamento: 13, ubigeo_provincia: "130600", nombre_provincia: "Otuzco"},
    {id_provincia: 119, id_departamento: 13, ubigeo_provincia: "130700", nombre_provincia: "Pacasmayo"},
    {id_provincia: 120, id_departamento: 13, ubigeo_provincia: "130800", nombre_provincia: "Pataz"},
    {id_provincia: 121, id_departamento: 13, ubigeo_provincia: "130900", nombre_provincia: "Sanchez Carrion"},
    {id_provincia: 122, id_departamento: 13, ubigeo_provincia: "131000", nombre_provincia: "Santiago de Chuco"},
    {id_provincia: 123, id_departamento: 13, ubigeo_provincia: "131100", nombre_provincia: "Gran Chimu"},
    {id_provincia: 124, id_departamento: 13, ubigeo_provincia: "131200", nombre_provincia: "Viru"},
    {id_provincia: 125, id_departamento: 14, ubigeo_provincia: "140100", nombre_provincia: "Chiclayo"},
    {id_provincia: 126, id_departamento: 14, ubigeo_provincia: "140200", nombre_provincia: "Ferreñafe"},
    {id_provincia: 127, id_departamento: 14, ubigeo_provincia: "140300", nombre_provincia: "Lambayeque"},
    {id_provincia: 128, id_departamento: 15, ubigeo_provincia: "150100", nombre_provincia: "Lima"},
    {id_provincia: 129, id_departamento: 15, ubigeo_provincia: "150200", nombre_provincia: "Barranca"},
    {id_provincia: 130, id_departamento: 15, ubigeo_provincia: "150300", nombre_provincia: "Cajatambo"},
    {id_provincia: 131, id_departamento: 15, ubigeo_provincia: "150400", nombre_provincia: "Canta"},
    {id_provincia: 132, id_departamento: 15, ubigeo_provincia: "150500", nombre_provincia: "Cañete"},
    {id_provincia: 133, id_departamento: 15, ubigeo_provincia: "150600", nombre_provincia: "Huaral"},
    {id_provincia: 134, id_departamento: 15, ubigeo_provincia: "150700", nombre_provincia: "Huarochiri"},
    {id_provincia: 135, id_departamento: 15, ubigeo_provincia: "150800", nombre_provincia: "Huaura"},
    {id_provincia: 136, id_departamento: 15, ubigeo_provincia: "150900", nombre_provincia: "Oyon"},
    {id_provincia: 137, id_departamento: 15, ubigeo_provincia: "151000", nombre_provincia: "Yauyos"},
    {id_provincia: 138, id_departamento: 16, ubigeo_provincia: "160100", nombre_provincia: "Maynas"},
    {id_provincia: 139, id_departamento: 16, ubigeo_provincia: "160200", nombre_provincia: "Alto Amazonas"},
    {id_provincia: 140, id_departamento: 16, ubigeo_provincia: "160300", nombre_provincia: "Loreto"},
    {id_provincia: 141, id_departamento: 16, ubigeo_provincia: "160400", nombre_provincia: "Mariscal Ramon Castilla"},
    {id_provincia: 142, id_departamento: 16, ubigeo_provincia: "160500", nombre_provincia: "Requena"},
    {id_provincia: 143, id_departamento: 16, ubigeo_provincia: "160600", nombre_provincia: "Ucayali"},
    {id_provincia: 144, id_departamento: 16, ubigeo_provincia: "160700", nombre_provincia: "Datem del Marañón"},
    {id_provincia: 145, id_departamento: 16, ubigeo_provincia: "160800", nombre_provincia: "Putumayo"},
    {id_provincia: 146, id_departamento: 17, ubigeo_provincia: "170100", nombre_provincia: "Tambopata"},
    {id_provincia: 147, id_departamento: 17, ubigeo_provincia: "170200", nombre_provincia: "Manu"},
    {id_provincia: 148, id_departamento: 17, ubigeo_provincia: "170300", nombre_provincia: "Tahuamanu"},
    {id_provincia: 149, id_departamento: 18, ubigeo_provincia: "180100", nombre_provincia: "Mariscal Nieto"},
    {id_provincia: 150, id_departamento: 18, ubigeo_provincia: "180200", nombre_provincia: "General Sanchez Cerro"},
    {id_provincia: 151, id_departamento: 18, ubigeo_provincia: "180300", nombre_provincia: "Ilo"},
    {id_provincia: 152, id_departamento: 19, ubigeo_provincia: "190100", nombre_provincia: "Pasco"},
    {id_provincia: 153, id_departamento: 19, ubigeo_provincia: "190200", nombre_provincia: "Daniel Alcides Carrion"},
    {id_provincia: 154, id_departamento: 19, ubigeo_provincia: "190300", nombre_provincia: "Oxapampa"},
    {id_provincia: 155, id_departamento: 20, ubigeo_provincia: "200100", nombre_provincia: "Piura"},
    {id_provincia: 156, id_departamento: 20, ubigeo_provincia: "200200", nombre_provincia: "Ayabaca"},
    {id_provincia: 157, id_departamento: 20, ubigeo_provincia: "200300", nombre_provincia: "Huancabamba"},
    {id_provincia: 158, id_departamento: 20, ubigeo_provincia: "200400", nombre_provincia: "Morropon"},
    {id_provincia: 159, id_departamento: 20, ubigeo_provincia: "200500", nombre_provincia: "Paita"},
    {id_provincia: 160, id_departamento: 20, ubigeo_provincia: "200600", nombre_provincia: "Sullana"},
    {id_provincia: 161, id_departamento: 20, ubigeo_provincia: "200700", nombre_provincia: "Talara"},
    {id_provincia: 162, id_departamento: 20, ubigeo_provincia: "200800", nombre_provincia: "Sechura"},
    {id_provincia: 163, id_departamento: 21, ubigeo_provincia: "210100", nombre_provincia: "Puno"},
    {id_provincia: 164, id_departamento: 21, ubigeo_provincia: "210200", nombre_provincia: "Azangaro"},
    {id_provincia: 165, id_departamento: 21, ubigeo_provincia: "210300", nombre_provincia: "Carabaya"},
    {id_provincia: 166, id_departamento: 21, ubigeo_provincia: "210400", nombre_provincia: "Chucuito"},
    {id_provincia: 167, id_departamento: 21, ubigeo_provincia: "210500", nombre_provincia: "El Collao"},
    {id_provincia: 168, id_departamento: 21, ubigeo_provincia: "210600", nombre_provincia: "Huancane"},
    {id_provincia: 169, id_departamento: 21, ubigeo_provincia: "210700", nombre_provincia: "Lampa"},
    {id_provincia: 170, id_departamento: 21, ubigeo_provincia: "210800", nombre_provincia: "Melgar"},
    {id_provincia: 171, id_departamento: 21, ubigeo_provincia: "210900", nombre_provincia: "Moho"},
    {id_provincia: 172, id_departamento: 21, ubigeo_provincia: "211000", nombre_provincia: "San Antonio de Putina"},
    {id_provincia: 173, id_departamento: 21, ubigeo_provincia: "211100", nombre_provincia: "San Roman"},
    {id_provincia: 174, id_departamento: 21, ubigeo_provincia: "211200", nombre_provincia: "Sandia"},
    {id_provincia: 175, id_departamento: 21, ubigeo_provincia: "211300", nombre_provincia: "Yunguyo"},
    {id_provincia: 176, id_departamento: 22, ubigeo_provincia: "220100", nombre_provincia: "Moyobamba"},
    {id_provincia: 177, id_departamento: 22, ubigeo_provincia: "220200", nombre_provincia: "Bellavista"},
    {id_provincia: 178, id_departamento: 22, ubigeo_provincia: "220300", nombre_provincia: "El Dorado"},
    {id_provincia: 179, id_departamento: 22, ubigeo_provincia: "220400", nombre_provincia: "Huallaga"},
    {id_provincia: 180, id_departamento: 22, ubigeo_provincia: "220500", nombre_provincia: "Lamas"},
    {id_provincia: 181, id_departamento: 22, ubigeo_provincia: "220600", nombre_provincia: "Mariscal Caceres"},
    {id_provincia: 182, id_departamento: 22, ubigeo_provincia: "220700", nombre_provincia: "Picota"},
    {id_provincia: 183, id_departamento: 22, ubigeo_provincia: "220800", nombre_provincia: "Rioja"},
    {id_provincia: 184, id_departamento: 22, ubigeo_provincia: "220900", nombre_provincia: "San Martin"},
    {id_provincia: 185, id_departamento: 22, ubigeo_provincia: "221000", nombre_provincia: "Tocache"},
    {id_provincia: 186, id_departamento: 23, ubigeo_provincia: "230100", nombre_provincia: "Tacna"},
    {id_provincia: 187, id_departamento: 23, ubigeo_provincia: "230200", nombre_provincia: "Candarave"},
    {id_provincia: 188, id_departamento: 23, ubigeo_provincia: "230300", nombre_provincia: "Jorge Basadre"},
    {id_provincia: 189, id_departamento: 23, ubigeo_provincia: "230400", nombre_provincia: "Tarata"},
    {id_provincia: 190, id_departamento: 24, ubigeo_provincia: "240100", nombre_provincia: "Tumbes"},
    {id_provincia: 191, id_departamento: 24, ubigeo_provincia: "240200", nombre_provincia: "Contralmirante Villar"},
    {id_provincia: 192, id_departamento: 24, ubigeo_provincia: "240300", nombre_provincia: "Zarumilla"},
    {id_provincia: 193, id_departamento: 25, ubigeo_provincia: "250100", nombre_provincia: "Coronel Portillo"},
    {id_provincia: 194, id_departamento: 25, ubigeo_provincia: "250200", nombre_provincia: "Atalaya"},
    {id_provincia: 195, id_departamento: 25, ubigeo_provincia: "250300", nombre_provincia: "Padre Abad"},
    {id_provincia: 196, id_departamento: 25, ubigeo_provincia: "250400", nombre_provincia: "Purus"},
    {id_provincia: 197, id_departamento: 26, ubigeo_provincia: "999900", nombre_provincia: "Extranjero"},
      ];
  constructor() { }

  getProvincias(){
    return this.provinciaList;
  }
}