import {Monturas} from './monturas.model';

export const USERS: Monturas[] = [
    {
        index: 1,
        id: '#MN0123',
        material: 'William Shipp',
        marca: 'Sandoval Griffith',
        codigo_1: 'GT891',
        codigo_2_interno: 'VB986',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Lima',
        status: 'Active',
        date: '14 Apr, 2020'
    },
    {
        index: 2,
        id: '#MN0122',
        material: 'Joe Hardy',
        marca: 'Norman Le',
        codigo_1: 'DF616',
        codigo_2_interno: 'HY457',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Arequipa',
        status: 'Active',
        date: '14 Apr, 2020'
    },
    {
        index: 3,
        id: '#MN0121',
        material: 'Thomas Hankins',
        marca: 'Kelly Vargas',
        codigo_1: 'BN653',
        codigo_2_interno: 'BN123',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Moquegua',
        status: 'Active',
        date: '13 Apr, 2020'
    },
    {
        index: 4,
        id: '#MN0120',
        material: 'Mary Frazier',
        marca: 'Martinez Byrne',
        codigo_1: 'SW639',
        codigo_2_interno: 'FR451',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Juliaca',
        status: 'Deactive',
        date: '13 Apr, 2020'
    },
    {
        index: 5,
        id: '#MN0119',
        material: 'Sam Perry',
        marca: 'Hicks Graham',
        codigo_1: 'ZX522',
        codigo_2_interno: 'XC648',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Puno',
        status: 'Active',
        date: '12 Apr, 2020'
    },
    {
        index: 6,
        id: '#MN0118',
        material: 'Muriel Myers',
        marca: 'Gibbs Malone',
        codigo_1: 'HY954',
        codigo_2_interno: 'KU197',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Arequipa',
        status: 'Deactive',
        date: '09 Apr, 2020'
    },
    {
        index: 7,
        id: '#MN0117',
        material: 'Jessie Jacobs',
        marca: 'Steele Rowland',
        codigo_1: 'FH374',
        codigo_2_interno: 'NV880',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Lima',
        status: 'Deactive',
        date: '09 Apr, 2020'
    },
    {
        index: 8,
        id: '#MN0116',
        material: 'Edward King',
        marca: 'Hart Estrada',
        codigo_1: 'CN620',
        codigo_2_interno: 'MK763',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Moquegua',
        status: 'Active',
        date: '08 Apr, 2020'
    },
    {
        index: 9,
        id: '#MN0115',
        material: 'Stacy Webster',
        marca: 'Jennings Johnston',
        codigo_1: 'BJ837',
        codigo_2_interno: 'DJ956',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Juliaca',
        status: 'Deactive',
        date: '07 Apr, 2020'
    },
    {
        index: 10,
        id: '#MN0114',
        material: 'Amy McDonald',
        marca: 'Garza Long',
        codigo_1: 'KI178',
        codigo_2_interno: 'WK434',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Puno',
        status: 'Active',
        date: '05 Apr, 2020'
    },
    {
        index: 11,
        id: '#MN0113',
        material: 'Terry Brown',
        marca: 'Valdez Mitchell',
        codigo_1: 'SH608',
        codigo_2_interno: 'PJ934',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Arequipa',
        status: 'Active',
        date: '02 Apr, 2020'
    },
    {
        index: 12,
        id: '#MN0112',
        material: 'Crissy Holland',
        marca: 'Haynes Moreno',
        codigo_1: 'DJ585',
        codigo_2_interno: 'ID273',
        precio_compra: '34.87',
        precio_venta: '56.90',
        talla: '26',
        cantidad: '34',
        sede: 'Trujillo',
        status: 'Deactive',
        date: '23 Mar, 2020'
    }
];

