import {User} from './list-users.model';

export const USERS: User[] = [
    {
        index: 1,
        id: '#MN0123',
        photo: 'assets/images/users/avatar-2.jpg',
        firstnames: 'William Shipp',
        lastnames: 'Sandoval Griffith',
        dni: '35488591',
        rol: 'Admin',
        sede: 'Lima',
        email: 'WilliamShipp@jourrapide.com',
        status: 'Active',
        date: '14 Apr, 2020'
    },
    {
        index: 2,
        id: '#MN0122',
        photo: '',
        firstnames: 'Joe Hardy',
        lastnames: 'Norman Le',
        dni: '66545616',
        rol: 'Vendedor',
        sede: 'Arequipa',
        email: 'JoeHardy@dayrep.com',
        status: 'Active',
        date: '14 Apr, 2020'
    },
    {
        index: 3,
        id: '#MN0121',
        photo: 'assets/images/users/avatar-3.jpg',
        firstnames: 'Thomas Hankins',
        lastnames: 'Kelly Vargas',
        dni: '45701653',
        rol: 'Vendedor',
        sede: 'Moquegua',
        email: 'ThomasHankins@dayrep.com',
        status: 'Active',
        date: '13 Apr, 2020'
    },
    {
        index: 4,
        id: '#MN0120',
        photo: 'assets/images/users/avatar-4.jpg',
        firstnames: 'Mary Frazier',
        lastnames: 'Martinez Byrne',
        dni: '63932451',
        rol: 'Contador',
        sede: 'Juliaca',
        email: 'MaryFrazier@armyspy.com',
        status: 'Deactive',
        date: '13 Apr, 2020'
    },
    {
        index: 5,
        id: '#MN0119',
        photo: '',
        firstnames: 'Sam Perry',
        lastnames: 'Hicks Graham',
        dni: '52203648',
        rol: 'Vendedor',
        sede: 'Puno',
        email: 'SamPerry@rhyta.com',
        status: 'Active',
        date: '12 Apr, 2020'
    },
    {
        index: 6,
        id: '#MN0118',
        photo: 'assets/images/users/avatar-5.jpg',
        firstnames: 'Muriel Myers',
        lastnames: 'Gibbs Malone',
        dni: '95488197',
        rol: 'Vendedor',
        sede: 'Arequipa',
        email: 'MurielMyers@rhyta.com',
        status: 'Deactive',
        date: '09 Apr, 2020'
    },
    {
        index: 7,
        id: '#MN0117',
        photo: '',
        firstnames: 'Jessie Jacobs',
        lastnames: 'Steele Rowland',
        dni: '37433880',
        rol: 'Contador',
        sede: 'Lima',
        email: 'JessieJacobs@teleworm.us',
        status: 'Deactive',
        date: '09 Apr, 2020'
    },
    {
        index: 8,
        id: '#MN0116',
        photo: 'assets/images/users/avatar-6.jpg',
        firstnames: 'Edward King',
        lastnames: 'Hart Estrada',
        dni: '62091763',
        rol: 'Contador',
        sede: 'Moquegua',
        email: 'EdwardKing@teleworm.us',
        status: 'Active',
        date: '08 Apr, 2020'
    },
    {
        index: 9,
        id: '#MN0115',
        photo: 'assets/images/users/avatar-7.jpg',
        firstnames: 'Stacy Webster',
        lastnames: 'Jennings Johnston',
        dni: '83724956',
        rol: 'Vendedor',
        sede: 'Juliaca',
        email: 'StacyWebster@armyspy.com',
        status: 'Deactive',
        date: '07 Apr, 2020'
    },
    {
        index: 10,
        id: '#MN0114',
        photo: '',
        firstnames: 'Amy McDonald',
        lastnames: 'Garza Long',
        dni: '17804434',
        rol: 'Vendedor',
        sede: 'Puno',
        email: 'AmyMcDonald@jourrapide.com',
        status: 'Active',
        date: '05 Apr, 2020'
    },
    {
        index: 11,
        id: '#MN0113',
        photo: '',
        firstnames: 'Terry Brown',
        lastnames: 'Valdez Mitchell',
        dni: '60861934',
        rol: 'Vendedor',
        sede: 'Arequipa',
        email: 'TerryBrown@dayrep.com',
        status: 'Active',
        date: '02 Apr, 2020'
    },
    {
        index: 12,
        id: '#MN0112',
        photo: 'assets/images/users/avatar-8.jpg',
        firstnames: 'Crissy Holland',
        lastnames: 'Haynes Moreno',
        dni: '58222273',
        rol: 'Contador',
        sede: 'Trujillo',
        email: 'CrissyHolland@armyspy.com',
        status: 'Deactive',
        date: '23 Mar, 2020'
    }
];

